function varagout = OBJECT_TRACKTEST(varargin)
gui_Singleton = 1;
gui_State = Struct('gui_Name',         nfilename,...
                   'gui_Singleton',    gui_Singleton,...
                   'gui_openingFon',   